apiVersion: v1
kind: ConfigMap
metadata:
  name: snapdrop-server-code
data:
  index.js: |
    const express = require('express');
    const app = express();
    const port = process.env.PORT || 80;

    app.use(express.json());
    app.use(express.static('public'));

    app.get('/api/peers', (req, res) => {
      res.json({ peers: [] });
    });

    app.post('/api/send', (req, res) => {
      res.json({ success: true });
    });

    app.listen(port, () => {
      console.log(`Server running on port ${port}`);
    });
  package.json: |
    {
      "name": "snapdrop-server",
      "version": "1.0.0",
      "dependencies": {
        "express": "^4.18.2"
      }
    } 